In [8]:
import pandas as pd
df = pd.read_excel('D:\Anime\Anime\ZImp\my_excel.xlsx')
df

,variable,Temperature,Precipitation Total,Wind Speed,Wind Direction
0,2020-11-08 00:00:00,-7.241812,0.0,51.716103,28.705948
1,2020-11-08 01:00:00,-7.511812,0.2,52.497080,27.795135
2,2020-11-08 02:00:00,-7.691812,0.3,52.165226,27.095550
3,2020-11-08 03:00:00,-7.821812,0.4,52.022180,24.968979
4,2020-11-08 04:00:00,-7.931812,0.3,53.557785,22.945724
...,...,...,...,...,...
187,2020-11-15 19:00:00,-5.081812,0.0,27.067116,283.851440
188,2020-11-15 20:00:00,-5.891812,0.0,24.336637,277.650670
189,2020-11-15 21:00:00,-6.471812,0.0,22.424270,275.527530
190,2020-11-15 22:00:00,-7.021812,0.0,21.388970,276.766170
191,2020-11-15 23:00:00,-7.991812,0.0,20.124610,280.304870

In [10]:
df['Temperature'].min()

-17.531813

In [11]:
df['Temperature'].max()

0.508188

In [12]:
df['variable'][df['Wind Speed']>24.336637]

0     2020-11-08 00:00:00
1     2020-11-08 01:00:00
2     2020-11-08 02:00:00
3     2020-11-08 03:00:00
4     2020-11-08 04:00:00
              ...
183   2020-11-15 15:00:00
184   2020-11-15 16:00:00
185   2020-11-15 17:00:00
186   2020-11-15 18:00:00
187   2020-11-15 19:00:00
Name: variable, Length: 94, dtype: datetime64[ns]

In [13]:
df['Wind Speed'].mean()

27.167234963541684

In [17]:
df[df.Temperature == df.Temperature.max()]

,variable,Temperature,Precipitation Total,Wind Speed,Wind Direction
61,2020-11-10 13:00:00,0.508188,0.0,32.978832,323.88068

In [18]:
df.describe()

       Temperature  Precipitation Total  Wind Speed  Wind Direction
count   192.000000           192.000000  192.000000      192.000000
mean     -7.894937             0.109896   27.167235      234.179370
std       4.383094             0.331040   14.497578       93.191025
min     -17.531813             0.000000    1.800000        2.231171
25%     -10.566812             0.000000   16.275819      188.592138
50%      -8.206812             0.000000   24.145463      225.000000
75%      -4.906812             0.000000   36.999262      318.978775
max       0.508188             2.100000   61.470463      358.814760

In [19]:
df.set_index('variable')

,Temperature,Precipitation Total,Wind Speed,Wind Direction
variable,,,,
2020-11-08 00:00:00,-7.241812,0.0,51.716103,28.705948
2020-11-08 01:00:00,-7.511812,0.2,52.497080,27.795135
2020-11-08 02:00:00,-7.691812,0.3,52.165226,27.095550
2020-11-08 03:00:00,-7.821812,0.4,52.022180,24.968979
2020-11-08 04:00:00,-7.931812,0.3,53.557785,22.945724
...,...,...,...,...
2020-11-15 19:00:00,-5.081812,0.0,27.067116,283.851440
2020-11-15 20:00:00,-5.891812,0.0,24.336637,277.650670
2020-11-15 21:00:00,-6.471812,0.0,22.424270,275.527530
2020-11-15 22:00:00,-7.021812,0.0,21.388970,276.766170
2020-11-15 23:00:00,-7.991812,0.0,20.124610,280.304870

In [26]:
df.set_index('variable',inplace = True)

In [27]:
df.loc['2020-11-15 19:00:00']

Temperature             -5.081812
Precipitation Total      0.000000
Wind Speed              27.067116
Wind Direction         283.851440
Name: 2020-11-15 19:00:00, dtype: float64

In [28]:
df

,Temperature,Precipitation Total,Wind Speed,Wind Direction
variable,,,,
2020-11-08 00:00:00,-7.241812,0.0,51.716103,28.705948
2020-11-08 01:00:00,-7.511812,0.2,52.497080,27.795135
2020-11-08 02:00:00,-7.691812,0.3,52.165226,27.095550
2020-11-08 03:00:00,-7.821812,0.4,52.022180,24.968979
2020-11-08 04:00:00,-7.931812,0.3,53.557785,22.945724
...,...,...,...,...
2020-11-15 19:00:00,-5.081812,0.0,27.067116,283.851440
2020-11-15 20:00:00,-5.891812,0.0,24.336637,277.650670
2020-11-15 21:00:00,-6.471812,0.0,22.424270,275.527530
2020-11-15 22:00:00,-7.021812,0.0,21.388970,276.766170
2020-11-15 23:00:00,-7.991812,0.0,20.124610,280.304870